name: CI
on:
  pull_request:
    paths:
      - 'server/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v3
      - name: Use Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: pytest tests/
